services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  whatwedo\SwissZip\Command\:
    resource: '../../Command/*'
    tags: ['console.command']

  whatwedo\SwissZip\:
    resource: '../../*'
    exclude: '../../Tests'

  whatwedo\SwissZip\EventListener\SwissZipTraitListener:
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }

  whatwedo\SwissZip\Repository\SwissZipRepositoryInterface:
    autowire: true
    public: true